### ISSUE TITLE
redux-eloquent integration?

### ISSUE THREAD

**Issue by asadakbar** [SevenOutman/rsuite-framework#1]
Are you going to be integrating redux-eloquent into this framework? I've been looking at orms for redux and came across redux-eloquent. 

Also, is this framework supposed to be used directly, or is it just to power create-rsuite-app?

Thanks for your hard work and great code!

**Comment by SevenOutman** [comment]
@asadakbar Thank you for being interested in my work. My goal is to integrate them together. As `rsuite-framework` needs orms, meanwhile `redux-eloquent` is not quite completed yet, current situation is that I'm developing framework's own orm that fits its use cases. But later i'd contribute those practice back into `redux-eloquent`.

Usage of this framework is not directly clone and start modifying. It's going to be shipped with a boilerplate generator which generates some specific directory structure and scripts that the framework requires. Current plan is to integrate it into [`create-rsuite-app`](https://github.com/rsuite/create-rsuite-app), the official boilerplate by rsuite team.

**Comment by asadakbar** [comment]
Got it. Thanks for replying. I've been investigating orms for redux to make my life easier handling relational data. I tried redux-eloquent a couple days ago but couldn't get it to work. Will you be putting up any example apps?

**Comment by SevenOutman** [comment]
@asadakbar Actually it's missing in `redux-eloquent`'s README that you should import its reducer from the package and add it into your `createStore` to get it work, which is quite essential. I'll add it into the readme, also you can dig into the source to see how it's supposed to be done.

**Comment by SevenOutman** [comment]
@asadakbar It's been updated along with some brief introduction to its APIs, you can [check it out](https://github.com/SevenOutman/redux-eloquent). Hope it helps.
